[build]
  command = "npm install && npm run build"
  publish = "build"

[build.environment]
  CI = "false"
  NODE_VERSION = "22.16.0"
  REACT_APP_API_URL = "https://intern4all-backend.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
