services:
  - type: web
    name: intern4all-frontend
    env: static
    buildCommand: npm install && npm run build && ls -la
    staticPublishPath: build
    envVars:
      - key: CI
        value: false
      - key: NODE_VERSION
        value: 22.16.0
      - key: REACT_APP_API_URL
        value: https://intern4all-backend.onrender.com/api
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
